::msgcat::mcset ru "Starting Wave..." "Запуск Волны..."
#::msgcat::mcset ru "Wave" "Волна"

::msgcat::mcset ru "Initiation of GUI elements..." "Инициализация элементов графического интерфейса..."
::msgcat::mcset ru "Binding hotkeys..." "Определение клавиатурных сокращений..."

::msgcat::mcset ru "File" "Файл"
::msgcat::mcset ru "Settings" "Настройки"
::msgcat::mcset ru "Help" "Помощь"

::msgcat::mcset ru "Exit" "Выход"

::msgcat::mcset ru "Support" "Обратная связь"
::msgcat::mcset ru "About" "О программе"

::msgcat::mcset ru "Fraisa diameter: " "Диаметр фрезы: "
::msgcat::mcset ru "Panel size by X: " "Размер фасада по X: "
::msgcat::mcset ru "Panel size by Y: " "Размер фасада по Y: "
::msgcat::mcset ru "Distance between lines: " "Расстояние между линиями контура: "
::msgcat::mcset ru "X margin: " "Отступ от края по X: "
::msgcat::mcset ru "Y margin: " "Отступ от края по Y: "
::msgcat::mcset ru "Min feed depth: " "Минимальная глубина фрезеровки: "
::msgcat::mcset ru "Max feed depth: " "Максимальная глубина фрезеровки: "
::msgcat::mcset ru "Radius: " "Радиус вершин: "
::msgcat::mcset ru "Wave mistiming: " "Отставание волн друг от друга: "
::msgcat::mcset ru "Length of wave lever: " "Длина плеча волны: "
::msgcat::mcset ru "Wave period: " "Период повторяемости: "
::msgcat::mcset ru "Height idle: " "Высота холостого перехода: "
::msgcat::mcset ru "Feed rate: " "Скорость рабочей подачи: "
::msgcat::mcset ru "Idle speed: " "Скорость холостого хода: "
::msgcat::mcset ru "Material tie-in speed: " "Скорость врезки в материал: "
::msgcat::mcset ru "Line count in block: " "Число линий в блоке: "
::msgcat::mcset ru "Count of blocks in lever: " "Разбиение плеча на количество блоков: "
::msgcat::mcset ru "Auto" "Авто"

::msgcat::mcset ru "Generate G-code" "Генерировать G-код"
::msgcat::mcset ru "Generate DXF" "Генерировать DXF"

::msgcat::mcset ru "Error!" "Ошибка!"

::msgcat::mcset ru "Doubled value of the length of wave lever is greater than panel size." "Удвоенное значение длины плеча волны больше размера фасада."

::msgcat::mcset ru "About Wave" "О программе Волна"
::msgcat::mcset ru "Help contents" "Разделы справки"

